# Values needed for Triton Inference Server

# Default values for triton
image:
  repository: nvcr.io/nvidia/tritonserver
  tag: 25.02-py3
  pullPolicy: Always

# GPU configuration
gpu:
  enabled: false
  num: 1
  type: nvidia-tesla-t4

# Models to be installed via a shared mounted host path (volume)
models: []
# Default annotations
annotations: {}
resources:
  limits:
    cpu: 2000m
    memory: 2048Mi
  requests:
    cpu: 400m
    memory: 256Mi

nodePort:
  enabled: false
  httpPort: 31333
  grpcPort: 31334
