# Values needed for Triton Inference Server

# The path to the models directory
modelRepositoryPath: /opt/teknoir/models
# Models to be installed via a shared mounted host path (volume)
models: []
# Default annotations
annotations:
  teknoir.org/managed-by: devstudio
