---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: triton
  namespace: {{ .Release.Namespace }}
  labels:
    app: triton
  annotations:
    {{- with $.Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: triton
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8002"
        {{- with $.Values.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        teknoir.org/app: triton
        app: triton
    spec:
{{- if .Values.gpu.enabled  }}
      nodeSelector:
        cloud.google.com/gke-accelerator: {{ .Values.gpu.type }}
{{- end }}
{{- if not (empty .Values.models) }}
      initContainers:
{{- range .Values.models }}
        - name: init-container-{{ .name }}
          image: {{ .image }}
          imagePullPolicy: Always
          volumeMounts:
            - name: models
              mountPath: "/models"
{{- end }}
{{- end }}
      containers:
        - name: triton
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "/opt/tritonserver/bin/tritonserver" ]
          args:
            [
              "--model-repository=/models",
              "--backend-directory=/opt/tritonserver/backends",
              "--log-verbose=1",
              "--log-info=true",
              "--log-warning=true",
              "--log-error=true",
            ]
          ports:
            - containerPort: 8000
              name: http
            - containerPort: 8001
              name: grpc
            - containerPort: 8002
              name: metrics
          livenessProbe:
            httpGet:
              path: /v2/health/live
              port: http
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /v2/health/ready
              port: http
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
{{- if .Values.gpu.enabled  }}
              nvidia.com/gpu: {{ .Values.gpu.num }}
{{- end }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
{{- if .Values.gpu.enabled  }}
              nvidia.com/gpu: {{ .Values.gpu.num }}
{{- end }}
          volumeMounts:
            - name: models
              mountPath: "/models"
      volumes:
        - name: models
          emptyDir: {}