---
apiVersion: v1
kind: Service
metadata:
  name: triton
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- toYaml $.Values.annotations | nindent 4 }}
spec:
  type: {{ if .Values.nodePort.enabled }}NodePort{{ else }}ClusterIP{{ end }}
  ports:
    - port: 8000
      targetPort: http
      name: http-inference-server
      {{- if .Values.nodePort.enabled }}
      nodePort: {{ .Values.nodePort.httpPort }}
      {{- end }}
    - port: 8001
      targetPort: grpc
      name: grpc-inference-server
      {{- if .Values.nodePort.enabled }}
      nodePort: {{ .Values.nodePort.grpcPort }}
      {{- end }}
    - port: 8002
      targetPort: metrics
      name: metrics-inference-server
  selector:
    app: triton
